# Generated by Django 4.2.19 on 2025-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
